### ISSUE TITLE
Default image-type to cos_containerd or use the GKE default

### ISSUE THREAD

**Issue by SergeyKanzhelev** [kubernetes-sigs/gcp-filestore-csi-driver#186]
In this https://github.com/kubernetes-sigs/gcp-filestore-csi-driver/blob/4fdf4c69accb84292a49e7b9652ef5e60dd07d6a/test/k8s-integration/main.go#L45 defaulting to `cos_containerd` or just rely on GKE default would be best

**Comment by mattcary** [comment]
I think we need an option to test on both cos & ubuntu. NFS system tools in the past have had distro-specific quirks so I think it's important we have an option to validate on both cos & ubuntu (like we're currently doing for the pd csi driver).

**Comment by SergeyKanzhelev** [comment]
Sure, I just suggest to change the default from `cos` to `cos_containerd`. For `ubuntu` it will be `ubuntu_containerd`

**Comment by mattcary** [comment]
Oh, I see. Thanks for clarifying, that makes sense.

**Comment by mattcary** [comment]
Closed via #204.
