### ISSUE TITLE
Changes are necessary for K8S 1.12

### ISSUE THREAD

**Issue by bukzor** [kubernetes-sigs/gcp-filestore-csi-driver#31]
Please see this bug, and the attendant patches to other CSI projects:
https://github.com/kubernetes/kubernetes/issues/68688

Apologies for the terseness here, but I'm pretty ignorant of what's going on here. I only know that filestore-csi "doesn't work" in k8s 1.12, and needs to be updated.

**Comment by msau42** [comment]
Thanks for filing the issue.  Will you be able to use 1.11 in the meantime?
/assign

**Comment by bukzor** [comment]
Yes.

It's becoming painful, however, as our infrastructure grows to deal with
the many and various shortcomings of hcl 11. And every issue about these
problems are closed with "fixed in 0.12".

**Comment by bukzor** [comment]
🤦‍♂️ I was thinking of terraform 0.11 vs 12.

kubernetes 1.12 adds alpha support for CSI SkipAttach, which will make filestore-csi significantly more reliable. It's a beta feature in 1.14. https://kubernetes-csi.github.io/docs/skip-attach.html
