### ISSUE TITLE
Dynamic PersistentVolume from pre-provisioned StorageClass

### ISSUE THREAD

**Issue by zeljkot** [kubernetes-sigs/gcp-filestore-csi-driver#418]
The documentation for the pre-provisioning is confusing. First, it states that it's necessary to create a StorageClass, and then it creates [PersistentVolume](https://github.com/kubernetes-sigs/gcp-filestore-csi-driver/blob/ad542caf0e1276e49016b3c33735de4515e8e318/examples/kubernetes/pre-provision/preprov-pv.yaml), but without referencing the StorageClass; rather, it references filestore directly. 

Is it possible to create PersistentVolume dynamically using PersistentVolumeClaim and StorageClass, without referencing the filestore?

**Comment by vascoalramos** [comment]
hello @zeljkot. were you able to create the storage class and PVC linking to the pre-provisioned Filestore instance?
