### ISSUE TITLE
Multiple pre-provisioned PVs on the same node

### ISSUE THREAD

**Issue by ianonavy** [kubernetes-sigs/gcp-filestore-csi-driver#464]
I am trying to reuse the same pre-provisioned Filestore instance and share across multiple namespaces within the same cluster. For each namespace, I create a PV and PVC that points to the same IP address and handle. All of the PVCs and PVs bind with no issue, but when a pod is scheduled to a node that already has the NFS mounted from a different namespace, I get an error like this:

>MountVolume.SetUp failed for volume "namespace3-shared-volume" : rpc error: code = Internal desc = mount "/var/lib/kubelet/pods/8b55fb58-037b-4d06-a658-22516200bb73/volumes/kubernetes.io\~csi/namespace3-shared-volume/mount" failed: mount failed: exit status 32 Mounting command: mount Mounting arguments: -t nfs -o bind /var/lib/kubelet/plugins/kubernetes.io/csi/pv/namespace3-shared-volume/globalmount /var/lib/kubelet/pods/8b55fb58-037b-4d06-a658-22516200bb73/volumes/kubernetes.io\~csi/namespace3-shared-volume/mount Output: mount: /var/lib/kubelet/pods/8b55fb58-037b-4d06-a658-22516200bb73/volumes/kubernetes.io\~csi/namespace3-shared-volume/mount: special device /var/lib/kubelet/plugins/kubernetes.io/csi/pv/namespace3-shared-volume/globalmount does not exist.

These correspond to the CSI driver logs:
```
I0403 16:05:31.158128       1 utils.go:55] GRPC call: /csi.v1.Node/NodePublishVolume
I0403 16:05:31.158284       1 utils.go:56] GRPC request: {"staging_target_path":"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/namespace3-shared-volume/globalmount","target_path":"/var/lib/kubelet/pods/8b55fb58-037b-4d06-a658-22516200bb73/volumes/kubernetes.io~csi/namespace3-shared-volume/mount","volume_capability":{"AccessType":{"Mount":{}},"access_mode":{"mode":5}},"volume_context":{"csi.storage.k8s.io/ephemeral":"false","csi.storage.k8s.io/pod.name":"redacted","csi.storage.k8s.io/pod.namespace":"namespace3","csi.storage.k8s.io/pod.uid":"8b55fb58-037b-4d06-a658-22516200bb73","csi.storage.k8s.io/serviceAccount.name":"redacted","ip":"10.X.X.X","volume":"share1"},"volume_id":"modeInstance/us-central1-c/filestore-instance-name/share1"}
E0403 16:05:31.160819       1 mount_linux.go:195] Mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t nfs -o bind /var/lib/kubelet/plugins/kubernetes.io/csi/pv/namespace3-shared-volume/globalmount /var/lib/kubelet/pods/8b55fb58-037b-4d06-a658-22516200bb73/volumes/kubernetes.io~csi/namespace3-shared-volume/mount
Output: mount: /var/lib/kubelet/pods/8b55fb58-037b-4d06-a658-22516200bb73/volumes/kubernetes.io~csi/namespace3-shared-volume/mount: special device /var/lib/kubelet/plugins/kubernetes.io/csi/pv/namespace3-shared-volume/globalmount does not exist.

E0403 16:05:31.160861       1 node.go:135] Mount "/var/lib/kubelet/pods/8b55fb58-037b-4d06-a658-22516200bb73/volumes/kubernetes.io~csi/namespace3-shared-volume/mount" failed, cleaning up
W0403 16:05:31.160906       1 mount_helper_common.go:34] Warning: Unmount skipped because path does not exist: /var/lib/kubelet/plugins/kubernetes.io/csi/pv/namespace3-shared-volume/globalmount
E0403 16:05:31.160935       1 utils.go:59] GRPC error: rpc error: code = Internal desc = mount "/var/lib/kubelet/pods/8b55fb58-037b-4d06-a658-22516200bb73/volumes/kubernetes.io~csi/namespace3-shared-volume/mount" failed: mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t nfs -o bind /var/lib/kubelet/plugins/kubernetes.io/csi/pv/namespace3-shared-volume/globalmount /var/lib/kubelet/pods/8b55fb58-037b-4d06-a658-22516200bb73/volumes/kubernetes.io~csi/namespace3-shared-volume/mount
Output: mount: /var/lib/kubelet/pods/8b55fb58-037b-4d06-a658-22516200bb73/volumes/kubernetes.io~csi/namespace3-shared-volume/mount: special device /var/lib/kubelet/plugins/kubernetes.io/csi/pv/namespace3-shared-volume/globalmount does not exist.
```

When the pods get scheduled on different nodes, the shared volume works as expected.

Is this the expected behavior? Are there any alternatives or workarounds that I should consider?

**Comment by ianonavy** [comment]
Quick update: I was able to get this to work using the [nfs-subdir-external-provisioner](https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner) instead. I set the `pathPattern` to a fixed value `shared-volume`, and that allowed the separate PVCs to all share the same subdir under the root NFS export.

**Comment by nstogner** [comment]
I have encountered similar issues. Thanks for the workaround!

**Comment by credativ-dar** [comment]
Are there any plans to document or fix this behavior?
