### ISSUE TITLE
Use external provisioner 2.0.x which provides a default-fstype flag

### ISSUE THREAD

**Issue by saikat-royc** [kubernetes-sigs/gcp-filestore-csi-driver#60]
Use external provisioner [change](https://github.com/kubernetes-csi/external-provisioner/pull/400) which provides a default-fstype flag. For filestore driver this should be set to 'nfs'.

Also have stricter check in ValidateVolumeCapabilities for fstype == 'nfs'.
https://github.com/kubernetes-sigs/gcp-filestore-csi-driver/blob/master/pkg/csi_driver/gcfs_driver.go#L154

Current implementation ignores the fstype passed by the CSI calls, and uses hard coded nfs type in mount operation.
https://github.com/kubernetes-sigs/gcp-filestore-csi-driver/blob/master/pkg/csi_driver/node.go#L216

**Comment by msau42** [comment]
Unsure if we should set a fstype. Then it may be hard to switch between nfs and smb in protocols in the future

**Comment by saikat-royc** [comment]
Smb type shares can be provided in the SC, which would override the default fstype set in provisioner. Thoughts?

**Comment by msau42** [comment]
I think a single share can support both smb or nfs and can dynamically decide which it wants to use depending on which OS it's being mounted on. I'm not sure I see a need for restricting the type on the PV yet.

In the CSI spec, we intended "" fstype for nfs-type systems.

**Comment by saikat-royc** [comment]
Ok so when we upgrade provisioner th 2.0.x we should be getting "" fstype in the volume capability.

**Comment by msau42** [comment]
correct
