### ISSUE TITLE
New release required

### ISSUE THREAD

**Issue by shankarkc** [kubernetes-sigs/gcp-filestore-csi-driver#62]
Post May there are some important changes merged to master ike the below two
Upgrade the driver to use CSI 1.3.x spec
PR for csi 1.3.0
Can you please release a new build for us from master branch?
Thanks
Shankar KC

**Comment by shankarkc** [comment]
@annapendleton  Can you please help with this?

**Comment by mattcary** [comment]
@shankarkc 

We will be pushing a new release in the next week or so that graduates this driver to beta. Does that fit with your timeline?
