### ISSUE TITLE
Add support for Filestore Zonal/Regional instances with 1-10Tb volume into Filestore CSI driver 

### ISSUE THREAD

**Issue by SehiiRohoza** [kubernetes-sigs/gcp-filestore-csi-driver#874]
Hello,

Accordingly to the official [documentation](https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/filestore-csi-driver):

> **Requirements**
>- To use the Filestore CSI driver, your clusters must use the proper GKE version number applicable to your service tier:
>   - Basic HDD with GKE version 1.21 or later
>   - Basic SSD with GKE version 1.21 or later
>   - Zonal (10 TiB to 100 TiB) with GKE version 1.27 or later
>   - Enterprise with GKE version 1.25 or later
>- To use the Filestore multishares capability, your clusters must use GKE version 1.25 or later.
>- The Filestore CSI driver is supported for clusters using Linux only; Windows Server nodes are not supported.
>- The minimum instance size for Filestore is at least 1 TiB. The minimum instance size depends on the Filestore service tier you - selected. To learn more, see [Service tiers](https://cloud.google.com/filestore/docs/service-tiers). 

Meanwhile, 10Tb volume is too expensive and overkill for many use cases. 

It'll be useful to have even basic/limited support of Filestore Zonal/Regional instances with 1-10Tb volume size in Filestore CSI driver with a clear information in the documentation.

**Comment by riteshghorse** [comment]
CC: @saikat-royc @eipi-one
